#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using an until loop

# Initialize a counter variable
count=0

# Loop until the count reaches 10
until [ "$count" -ge 10 ]; do
  echo "Best School"
  # Increment the counter
  count=$((count + 1))
done
