#!/usr/bin/env bash
# Find the PID of the 7-highlander process using ps and grep
PID=$(ps -ef | grep "[./]7-highlander" | awk '{print $2}')

# If a PID is found, send SIGTERM
if [ -n "$PID" ]; then
    kill -TERM "$PID"
fi
