#!/usr/bin/env bash
# Script: 8-beheaded_process
# Purpose: Kill the 7-highlander process using SIGKILL (signal 9).
# Context: pgrep is not available, so we use ps + grep and disable ShellCheck warning SC2009.
# SIGKILL ensures the process is forcibly terminated and cannot ignore the signal.

# shellcheck disable=SC2009
PID=$(ps -e | grep "[./]7-highlander" | awk '{print $1}')

if [ -n "$PID" ]; then
    kill -9 "$PID"
fi
