#!/usr/bin/env bash
# This script provides information about a file named 'school'.

FILE="school"

# Check for existence
if [ -e "$FILE" ]; then
  echo "$FILE file exists"

  # If the file exists, perform further checks
  if [ -s "$FILE" ]; then
    echo "$FILE file is not empty"
  else
    echo "$FILE file is empty"
  fi

  # Check if it's a regular file
  if [ -f "$FILE" ]; then
    echo "$FILE is a regular file"
  fi

else
  echo "$FILE file does not exist"
fi
